/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721UserFile__factory } from "./ERC721UserFile__factory";
export { UserFileAccess__factory } from "./UserFileAccess__factory";
